const userInfo = {
  name: "Kevin Jiao",
  siteTitle: "Kevin Jiao",
  metaPic: "https://og-image.vercel.app/**Kevin%20Jiao**.png?theme=dark&md=1&fontSize=225px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-white-logo.svg&images=https%3A%2F%2Fraw.githubusercontent.com%2Ftwitter%2Ftwemoji%2Fba9c621af05213b19107d27a4b60afed888033dc%2Fsvg%2F1f414.svg&images=https%3A%2F%2Fraw.githubusercontent.com%2Fgooglefonts%2Fnoto-emoji%2F9a5261d871451f9b5183c93483cbd68ed916b1e9%2Fsvg%2Femoji_u1f99c.svg&widths=350&widths=350&widths=350&heights=350&heights=350&heights=350",
  siteLinks: ["About", "Projects", "Misc"],
  projects: [
    {
      imageURL: "/images/animations/project1/Change1.PNG",
      title: "Computer Animation Projects",
      description: "Projects made in Computer Animation class",
      githubLink: "",
      deployLink: "/projects/animations",
      tags: ["Autodesk Maya"],
      external: false,
    },
    {
      imageURL: "/images/site.PNG",
      title: "KXJiao.github.io",
      description: "My personal site, currently work in progress",
      githubLink: "https://github.com/KXJiao/KXJiao.github.io",
      deployLink: "/",
      tags: ["Next.js", "Typescript"],
      external: false,
    },
  ],
  animations: [
    {
      imageURL: "/images/animations/project1/Change2.PNG",
      title: "Project 1: Planet Animation",
      description: "First Project: Solar System animation",
      githubLink: "",
      deployLink: "/projects/animations/project1",
      tags: [],
      external: false,
    },
    {
      imageURL: "/images/animations/project2/Smooth2.PNG",
      title: "Project 2: Treasure Chest",
      description: "Second Project: Treasure chest modeling",
      githubLink: "",
      deployLink: "/projects/animations/project2",
      tags: [],
      external: false,
    },
    {
      imageURL: "/images/animations/project3/icon.png",
      title: "Project 3: Bouncy Ball",
      description: "Third Project: 12 Principles of Animation",
      githubLink: "",
      deployLink: "/projects/animations/project3",
      tags: [],
      external: false,
    },
    {
      imageURL: "/images/animations/project4/icon.png",
      title: "Project 4: Rube Goldberg",
      description: "Fourth Project: Maya FX",
      githubLink: "",
      deployLink: "/projects/animations/project4",
      tags: [],
      external: false,
    },
    {
      imageURL: "/images/animations/project5/icon.png",
      title: "Project 5: Python Scripting",
      description: "Fifth Project: Mash + Python",
      githubLink: "",
      deployLink: "/projects/animations/project5",
      tags: [],
      external: false,
    },
  ],
  socialLinks: {
    linkedin: "https://linkedin.com/in/kxjiao",
    github: "https://github.com/KXJiao",
  },
};

export default userInfo;
